-- =====================================================================
-- GestorPro · Estructura de la base de datos (sin datos)
-- =====================================================================
-- Qué hace: crea en un proyecto NUEVO de Supabase todo lo que necesita GestorPro:
--   · 16 tablas (productos, lotes, ventas, fiados, caja, mermas, proveedores...)
--   · índices, 12 funciones, 2 vistas de reportes y 7 triggers
--     (descuento de stock, estado de fiados, abonos que entran a caja...)
--   · los datos iniciales: la ficha de la empresa y un usuario administrador
--
-- Cómo usarlo (una sola vez, en un proyecto de Supabase vacío):
--   1. Entra a tu proyecto en https://supabase.com
--   2. Menú izquierdo → SQL Editor → New query
--   3. Pega todo este archivo y pulsa "Run"
--   4. Después ejecuta también storage_empresa_logos.sql (para el logo)
--
-- Primer ingreso a GestorPro:
--   Usuario:    admin
--   Contraseña: cambiar123
--   Cámbiala enseguida en Configuración → Gestión de usuarios.
--
-- Si algo falla, no se crea nada a medias: todo va en una sola transacción.
-- =====================================================================

BEGIN;

SET check_function_bodies = false;
SET client_min_messages = warning;

-- ---------------------------------------------------------------------
-- 1. TABLAS
-- ---------------------------------------------------------------------

CREATE TABLE public."batches" (
  "id" bigint NOT NULL,
  "product_id" bigint,
  "quantity" numeric,
  "initial_quantity" numeric,
  "expiration_date" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "cost_total" numeric,
  "cost_unit" numeric,
  "supplier" text,
  "is_active" bigint,
  "is_synced" bigint,
  "provider_id" text,
  "document_ref" text
);

CREATE TABLE public."cash_movements" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" text,
  "type" text,
  "amount" double precision,
  "description" text,
  "created_at" timestamp with time zone,
  "is_synced" bigint,
  "payment_type" text,
  "flujo" text
);

CREATE TABLE public."cash_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "opening_balance" numeric,
  "closing_balance" numeric,
  "expected_balance" numeric,
  "status" text,
  "opened_at" timestamp with time zone,
  "closed_at" text,
  "justification" text,
  "is_synced" bigint,
  "opening_yape" text,
  "opening_card" text,
  "closing_yape" numeric,
  "closing_card" numeric,
  "expected_yape" numeric,
  "expected_card" numeric
);

CREATE TABLE public."categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text,
  "is_synced" bigint
);

CREATE TABLE public."customers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text,
  "dni" text,
  "default_pay_date" text,
  "created_at" timestamp with time zone,
  "is_synced" bigint
);

CREATE TABLE public."debt_payments" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "fiado_id" bigint,
  "customer_id" bigint,
  "amount" numeric,
  "payment_type" text,
  "created_at" timestamp with time zone,
  "session_id" bigint,
  "sale_id" text,
  "amount_cash" numeric,
  "amount_yape" numeric,
  "amount_transfer" numeric,
  "amount_card" numeric,
  "is_synced" bigint
);

CREATE TABLE public."empleados" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nombre" text NOT NULL,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "rol" text DEFAULT 'Cajero'::text,
  "estado" text DEFAULT 'ACTIVO'::text,
  "permisos" jsonb,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."empresa_config" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nombre_empresa" text DEFAULT 'EVICAMP'::text,
  "ruc" text,
  "direccion" text,
  "telefono" text,
  "logo_url" text,
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."fiados" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sale_id" bigint,
  "customer_id" bigint,
  "customer_name" text,
  "amount" numeric,
  "date_given" timestamp with time zone,
  "date_paid" text,
  "expected_pay_date" text,
  "status" text,
  "paid_amount" numeric,
  "is_synced" bigint
);

CREATE TABLE public."inventory_movements" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" bigint,
  "product_id" bigint,
  "product_name" text,
  "change_amount" numeric,
  "previous_quantity" numeric,
  "new_quantity" numeric,
  "operation_type" text,
  "reason" text,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "user" text,
  "is_synced" bigint
);

CREATE TABLE public."products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text,
  "quantity" numeric,
  "price" numeric,
  "code" text,
  "barcode" text,
  "category" text,
  "cost_price" numeric,
  "min_stock" numeric,
  "created_at" timestamp with time zone DEFAULT now(),
  "control_type" text,
  "weight_unit" text,
  "unit_weight" text,
  "is_active" bigint,
  "discount_percent" numeric,
  "ref_unit" text,
  "ref_qty" bigint,
  "is_synced" bigint,
  "sunat_unit_code" text,
  "sunat_igv_type" bigint,
  "image_path" text,
  "image_url" text,
  "unit" text
);

CREATE TABLE public."providers" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "ruc" character varying(20) NOT NULL,
  "razon_social" character varying(255) NOT NULL,
  "nombre_comercial" character varying(255),
  "telefono" character varying(50),
  "email" character varying(100),
  "direccion" text,
  "estado" character varying(20) DEFAULT 'ACTIVO'::character varying,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."sale_details" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sale_id" bigint,
  "product_id" bigint,
  "product_name" text,
  "quantity" numeric,
  "price_at_moment" numeric,
  "subtotal" numeric,
  "is_synced" bigint,
  "cost_at_moment" numeric
);

CREATE TABLE public."sales" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "total" double precision,
  "payment_type" text,
  "created_at" timestamp with time zone,
  "payment_meta" text,
  "reference" text,
  "amount_cash" double precision,
  "amount_yape" numeric,
  "amount_transfer" numeric,
  "amount_card" numeric,
  "amount_credit" numeric,
  "is_synced" bigint,
  "doc_type" bigint,
  "doc_serial" text,
  "doc_number" text,
  "taxable_amount" numeric,
  "igv_amount" numeric,
  "total_exempt" numeric,
  "sunat_status" text,
  "sunat_hash" text
);

CREATE TABLE public."waste" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" bigint,
  "product_id" bigint,
  "product_name" text,
  "quantity" double precision,
  "cost_unit" double precision,
  "total_loss" double precision,
  "reason" text,
  "notes" text,
  "user" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "is_synced" bigint,
  "previous_quantity" double precision,
  "new_quantity" double precision
);

-- ---------------------------------------------------------------------
-- 2. CLAVES PRIMARIAS, ÚNICAS Y VALIDACIONES
-- ---------------------------------------------------------------------
ALTER TABLE ONLY public.batches ADD CONSTRAINT "batches_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.cash_movements ADD CONSTRAINT "cash_movements_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.cash_sessions ADD CONSTRAINT "cash_sessions_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.categories ADD CONSTRAINT "categories_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.customers ADD CONSTRAINT "customers_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.debt_payments ADD CONSTRAINT "debt_payments_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.empleados ADD CONSTRAINT "empleados_email_key" UNIQUE (email);
ALTER TABLE ONLY public.empleados ADD CONSTRAINT "empleados_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.empresa_config ADD CONSTRAINT "empresa_config_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.fiados ADD CONSTRAINT "fiados_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_movements ADD CONSTRAINT "inventory_movements_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.products ADD CONSTRAINT "products_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.providers ADD CONSTRAINT "providers_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.sale_details ADD CONSTRAINT "sale_details_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.sales ADD CONSTRAINT "sales_pkey" PRIMARY KEY (id);
ALTER TABLE ONLY public.waste ADD CONSTRAINT "waste_pkey" PRIMARY KEY (id);

-- ---------------------------------------------------------------------
-- 3. ÍNDICES
-- ---------------------------------------------------------------------
CREATE INDEX idx_cash_movements_created_at ON public.cash_movements USING btree (created_at);
CREATE INDEX idx_details_composite ON public.sale_details USING btree (sale_id, product_id);
CREATE INDEX idx_sale_details_sale_id ON public.sale_details USING btree (sale_id);
CREATE INDEX idx_sales_created_at ON public.sales USING btree (created_at);
CREATE INDEX idx_sales_fecha_estado ON public.sales USING btree (created_at, sunat_status);
CREATE UNIQUE INDEX idx_uq_product_barcode_active ON public.products USING btree (barcode) WHERE ((is_active = '1'::bigint) AND (barcode IS NOT NULL) AND (barcode <> ''::text));
CREATE UNIQUE INDEX idx_uq_product_code_active ON public.products USING btree (code) WHERE ((is_active = '1'::bigint) AND (code IS NOT NULL) AND (code <> ''::text));
CREATE INDEX idx_waste_created_at ON public.waste USING btree (created_at);

-- ---------------------------------------------------------------------
-- 4. FUNCIONES
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_edit_batch(p_batch_id text, p_new_qty numeric, p_new_cost numeric, p_user_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_product_id bigint;
    v_product_name text;
    v_old_qty numeric;
    v_diff numeric;
BEGIN
    -- 1. Capturar datos antiguos
    SELECT product_id, quantity INTO v_product_id, v_old_qty 
    FROM public.batches 
    WHERE id = p_batch_id::bigint AND is_active = 1;
    
    IF NOT FOUND THEN RETURN; END IF;
    
    SELECT name INTO v_product_name FROM public.products WHERE id = v_product_id;
    
    -- 2. Calcular la diferencia matemática
    v_diff := p_new_qty - v_old_qty;

    -- 3. Actualizar el Lote
    UPDATE public.batches 
    SET quantity = p_new_qty, cost_unit = p_new_cost 
    WHERE id = p_batch_id::bigint;

    -- 4. Re-sincronizar el stock global del Producto
    UPDATE public.products SET quantity = (
        SELECT COALESCE(SUM(quantity), 0) 
        FROM public.batches 
        WHERE product_id = v_product_id AND is_active = 1
    ) WHERE id = v_product_id;

    -- 5. Registrar el movimiento en el historial solo si la cantidad cambió
    IF v_diff <> 0 THEN
        INSERT INTO public.inventory_movements (
            batch_id, product_id, product_name, change_amount, previous_quantity, new_quantity, 
            operation_type, reason, "user", created_at, is_synced
        ) VALUES (
            p_batch_id::bigint, v_product_id, v_product_name, v_diff, v_old_qty, p_new_qty, 
            'AJUSTE', 'Edición manual de lote', p_user_name, NOW(), '1'
        );
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_reduce_stock_from_sales()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_qty_to_deduct NUMERIC;
    v_current_stock NUMERIC;
    v_batch_record record;
    v_deducted NUMERIC;
    v_is_consumo BOOLEAN;
    v_costo_real NUMERIC := 0; -- 🚨 VARIABLE NUEVA PARA RASTREAR COSTO
BEGIN
    BEGIN
        SELECT (COALESCE(unit, '') = 'CONSUMO' OR COALESCE(control_type, '') = 'CONSUMPTION') 
        INTO v_is_consumo 
        FROM public.products WHERE id = NEW.product_id;

        IF v_is_consumo = TRUE THEN 
            RETURN NEW; 
        END IF;

        v_qty_to_deduct := ABS(COALESCE(NEW.quantity, 0));
        IF v_qty_to_deduct = 0 THEN 
            RETURN NEW; 
        END IF;

        UPDATE public.products
        SET quantity = COALESCE(quantity, 0) - v_qty_to_deduct
        WHERE id = NEW.product_id
        RETURNING COALESCE(quantity, 0) INTO v_current_stock;

        FOR v_batch_record IN 
            -- 🚨 CORRECCIÓN: Ahora también extraemos el cost_unit del lote
            SELECT id, COALESCE(quantity, 0) as qty, COALESCE(cost_unit, 0) as cost 
            FROM public.batches 
            WHERE product_id = NEW.product_id AND COALESCE(quantity, 0) > 0 
            ORDER BY created_at ASC, id ASC
            FOR UPDATE
        LOOP
            IF v_qty_to_deduct <= 0 THEN EXIT; END IF;

            IF v_batch_record.qty >= v_qty_to_deduct THEN
                UPDATE public.batches SET quantity = (v_batch_record.qty - v_qty_to_deduct) WHERE id = v_batch_record.id;
                v_deducted := v_qty_to_deduct;
                v_qty_to_deduct := 0;
            ELSE
                UPDATE public.batches SET quantity = 0 WHERE id = v_batch_record.id;
                v_deducted := v_batch_record.qty;
                v_qty_to_deduct := v_qty_to_deduct - v_batch_record.qty;
            END IF;

            -- 🚨 EL MOTOR GUARDA EL COSTO EXACTO DEL LOTE (Previene error de Costo Alto)
            v_costo_real := v_batch_record.cost;

            INSERT INTO public.inventory_movements (
                batch_id, product_id, product_name, change_amount,
                previous_quantity, new_quantity, operation_type, reason, notes, created_at, "user", is_synced
            ) VALUES (
                v_batch_record.id, NEW.product_id, NEW.product_name, -v_deducted,
                (v_current_stock + v_deducted), v_current_stock,
                'VENTA', 'Venta POS', 'Ticket #' || NEW.sale_id::text, NOW(), 'Sistema', 1
            );
        END LOOP;

        -- 🚨 INYECCIÓN AL DETALLE DE VENTA: Si el sistema encontró un costo real en el lote,
        -- lo graba a fuego en sale_details para que Utilidades no tenga que adivinar.
        IF v_costo_real > 0 THEN
            NEW.cost_at_moment := v_costo_real;
        END IF;

    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'Error interno al reducir stock: %', SQLERRM;
    END;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_register_fiado_payment_in_cash()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO public.cash_movements (
        session_id, type, amount, description, payment_type, created_at, is_synced, flujo
    ) VALUES (
        NEW.session_id::text,
        'INGRESO',
        NEW.amount,
        'ABONO DE FIADO / Cliente ID: ' || COALESCE(NEW.customer_id::text, 'General'),
        NEW.payment_type,
        NEW.created_at,
        1,
        'INGRESO_FIADO'
    );
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_restore_stock_on_waste_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_current_stock NUMERIC;
    v_clean_batch BIGINT;
    v_clean_qty NUMERIC;
BEGIN
    v_clean_batch := OLD.batch_id;
    v_clean_qty := ABS(COALESCE(OLD.quantity, 0));

    UPDATE public.products
    SET quantity = COALESCE(quantity, 0) + v_clean_qty
    WHERE id = OLD.product_id
    RETURNING quantity INTO v_current_stock;

    INSERT INTO public.inventory_movements (
        batch_id, product_id, product_name, change_amount,
        previous_quantity, new_quantity, operation_type, reason, notes, created_at, "user", is_synced
    ) VALUES (
        v_clean_batch, OLD.product_id, OLD.product_name, v_clean_qty,
        (v_current_stock - v_clean_qty), v_current_stock,
        'ENTRADA', 'Anulación Gasto/Merma', 'Sistema BD: Restauración automática.', NOW(), 'Sistema', 0
    );

    IF v_clean_batch IS NOT NULL THEN
        UPDATE public.batches
        SET quantity = COALESCE(quantity, 0) + v_clean_qty
        WHERE id = v_clean_batch;
    END IF;

    RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_sanitize_product_codes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    -- Si el código de barras está vacío o solo contiene espacios, mutarlo a NULL
    IF TRIM(NEW.barcode) = '' THEN
        NEW.barcode := NULL;
    END IF;

    -- Si el código interno (SKU) está vacío, mutarlo a NULL
    IF TRIM(NEW.code) = '' THEN
        NEW.code := NULL;
    END IF;

    -- Opcional (Recomendado): Forzar el nombre a mayúsculas y quitar espacios en blanco
    -- para mantener consistencia visual y geométrica en las búsquedas
    IF NEW.name IS NOT NULL THEN
        NEW.name := UPPER(TRIM(NEW.name));
    END IF;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_soft_delete_batch(p_batch_id text, p_user_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_product_id bigint;
    v_product_name text;
    v_quantity numeric;
BEGIN
    SELECT product_id, quantity INTO v_product_id, v_quantity 
    FROM public.batches WHERE id = p_batch_id::bigint;
    
    IF NOT FOUND THEN RETURN; END IF;
    SELECT name INTO v_product_name FROM public.products WHERE id = v_product_id;

    -- Borrado lógico y recálculo matemático
    UPDATE public.batches SET is_active = 0, quantity = 0 WHERE id = p_batch_id::bigint;
    
    UPDATE public.products SET quantity = (
        SELECT COALESCE(SUM(quantity), 0) FROM public.batches WHERE product_id = v_product_id AND is_active = 1
    ) WHERE id = v_product_id;

    -- Historial
    INSERT INTO public.inventory_movements (
        batch_id, product_id, product_name, change_amount, previous_quantity, new_quantity, 
        operation_type, reason, "user", created_at, is_synced
    ) VALUES (
        p_batch_id::bigint, v_product_id, v_product_name, -v_quantity, v_quantity, 0, 
        'AJUSTE', 'Retiro de Lote (Soft Delete)', p_user_name, NOW(), '1'
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_soft_delete_product(p_product_id text, p_user_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_product_name text;
    v_total_qty numeric;
BEGIN
    -- Validar existencia convirtiendo el texto a ID internamente
    SELECT name, quantity INTO v_product_name, v_total_qty 
    FROM public.products 
    WHERE id = p_product_id::bigint;

    IF NOT FOUND THEN 
        RAISE EXCEPTION 'Producto ID % no encontrado.', p_product_id;
    END IF;

    -- Borrado lógico
    UPDATE public.products 
    SET is_active = '0', quantity = 0 
    WHERE id = p_product_id::bigint;

    UPDATE public.batches 
    SET is_active = 0, quantity = 0 
    WHERE product_id = p_product_id::bigint;

    -- Trazabilidad
    IF v_total_qty > 0 THEN
        INSERT INTO public.inventory_movements (
            product_id, product_name, change_amount, previous_quantity, new_quantity, 
            operation_type, reason, "user", created_at, is_synced
        ) VALUES (
            p_product_id::bigint, v_product_name, -v_total_qty, v_total_qty, 0, 
            'AJUSTE', 'Eliminación del sistema (Soft Delete)', p_user_name, NOW(), '1'
        );
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_sync_all_sequences()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_table RECORD;
    v_seq TEXT;
    v_max_id BIGINT;
BEGIN
    -- Iterar sobre todas las tablas del esquema 'public'
    FOR v_table IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    LOOP
        -- Buscar si la tabla tiene una secuencia atada a la columna 'id'
        v_seq := pg_get_serial_sequence('public.' || v_table.table_name, 'id');
        
        IF v_seq IS NOT NULL THEN
            -- Obtener el ID máximo actual de la tabla
            EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM public.%I', v_table.table_name) INTO v_max_id;
            
            -- Sincronizar la secuencia estrictamente con el ID máximo
            IF v_max_id > 0 THEN
                EXECUTE format('SELECT setval(%L, %s)', v_seq, v_max_id);
            END IF;
        END IF;
    END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.soft_delete_batch(p_batch_id text, p_user_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_product_id text;
    v_product_name text;
    v_quantity numeric;
BEGIN
    SELECT product_id, quantity INTO v_product_id, v_quantity FROM batches WHERE id = p_batch_id;
    IF NOT FOUND THEN RETURN; END IF;

    SELECT name INTO v_product_name FROM products WHERE id = v_product_id;

    UPDATE batches SET is_active = 0, quantity = 0 WHERE id = p_batch_id;

    UPDATE products SET quantity = (
        SELECT COALESCE(SUM(quantity), 0) FROM batches WHERE product_id = v_product_id AND is_active = 1
    ) WHERE id = v_product_id;

    INSERT INTO inventory_movements (
        batch_id, product_id, product_name, change_amount, previous_quantity, new_quantity, operation_type, reason, "user", is_synced
    ) VALUES (
        p_batch_id, v_product_id, v_product_name, -v_quantity, v_quantity, 0, 'AJUSTE', 'Eliminación de Lote', p_user_name, '1'
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.trg_sync_product_name()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.name <> OLD.name THEN
        -- Se elimina la actualización a "batches" porque esa tabla no almacena el nombre.
        UPDATE public.inventory_movements SET product_name = NEW.name WHERE product_id = NEW.id;
        UPDATE public.waste SET product_name = NEW.name WHERE product_id = NEW.id;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_fiado_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_fiado_id BIGINT;
    v_total_paid NUMERIC;
    v_amount NUMERIC;
BEGIN
    -- 1. Extraemos el identificador de la cuenta con seguridad
    v_fiado_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.fiado_id ELSE NEW.fiado_id END;

    -- 2. PROTECCIÓN CONTRA NULOS: Si el pago no está enlazado a un crédito específico, cancelamos la mutación 
    -- y dejamos que el pago entre a la caja sin romper el sistema de fiados.
    IF v_fiado_id IS NULL THEN
        RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
    END IF;

    -- 3. Calcular la liquidez real inyectada
    SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
    FROM public.debt_payments
    WHERE fiado_id = v_fiado_id;

    -- 4. Extraer el valor total matriz de la deuda
    SELECT amount INTO v_amount
    FROM public.fiados
    WHERE id = v_fiado_id;

    -- 5. Lógica de Mutación Matemática
    IF v_amount IS NOT NULL THEN
        UPDATE public.fiados
        SET 
            paid_amount = v_total_paid,
            status = CASE 
                WHEN v_total_paid >= (v_amount - 0.05) THEN 'CANCELADO'
                ELSE 'PENDIENTE'
            END,
            date_paid = CASE 
                WHEN v_total_paid >= (v_amount - 0.05) THEN NOW()::text
                ELSE NULL
            END
        WHERE id = v_fiado_id;
    END IF;

    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_stock_from_waste()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.products
    SET quantity = quantity + NEW.quantity
    WHERE id = NEW.product_id;
    RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------
-- 5. VISTAS
-- ---------------------------------------------------------------------

CREATE VIEW public."reporte_utilidad_hoy" AS
WITH detalleventas AS (
         SELECT sd.product_id,
            sd.product_name AS producto,
            sum(sd.quantity) AS cantidad_vendida,
            COALESCE(max(sd.cost_at_moment), max(p.cost_price), 0::numeric) AS costo_unitario,
            sum(sd.subtotal) AS ingresos_totales
           FROM public.sale_details sd
             JOIN public.sales s ON sd.sale_id = s.id
             JOIN public.products p ON sd.product_id = p.id
          WHERE s.created_at::date = CURRENT_DATE AND s.sunat_status <> 'ANULADO'::text
          GROUP BY sd.product_id, sd.product_name
        ), calculobruto AS (
         SELECT COALESCE(sum(detalleventas.ingresos_totales), 0::numeric) AS ingresos_totales,
            COALESCE(sum(detalleventas.cantidad_vendida * detalleventas.costo_unitario), 0::numeric) AS costo_total_mercaderia
           FROM detalleventas
        ), totalmermas AS (
         SELECT COALESCE(sum(waste.total_loss), 0::double precision) AS mermas_hoy
           FROM public.waste
          WHERE waste.created_at::date = CURRENT_DATE
        )
 SELECT CURRENT_DATE AS fecha,
    cb.ingresos_totales AS "Ingreso Bruto",
    cb.costo_total_mercaderia AS "Costo Inversión",
    tm.mermas_hoy AS "Pérdida Mermas",
    (cb.ingresos_totales - cb.costo_total_mercaderia)::double precision - tm.mermas_hoy AS "UTILIDAD NETA REAL"
   FROM calculobruto cb,
    totalmermas tm;

CREATE VIEW public."reporte_utilidades" AS
SELECT s.id AS sale_id,
    s.created_at,
    s.total AS ingreso_total,
    s.sunat_status,
    COALESCE(sum(d.quantity * d.cost_at_moment), 0::numeric) AS costo_total_venta,
    s.total - COALESCE(sum(d.quantity * d.cost_at_moment), 0::numeric)::double precision AS utilidad_bruta
   FROM public.sales s
     LEFT JOIN public.sale_details d ON s.id = d.sale_id
  WHERE s.sunat_status <> 'ANULADO'::text
  GROUP BY s.id, s.created_at, s.total, s.sunat_status;

-- ---------------------------------------------------------------------
-- 6. RELACIONES ENTRE TABLAS (CLAVES FORÁNEAS)
-- ---------------------------------------------------------------------
ALTER TABLE ONLY public.batches ADD CONSTRAINT "batches_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sale_details ADD CONSTRAINT "sale_details_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.waste ADD CONSTRAINT "waste_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES public.batches(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.waste ADD CONSTRAINT "waste_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

-- ---------------------------------------------------------------------
-- 7. TRIGGERS (automatismos de stock, fiados y caja)
-- ---------------------------------------------------------------------
CREATE TRIGGER tr_fiado_payment_to_cash AFTER INSERT ON public.debt_payments FOR EACH ROW EXECUTE FUNCTION public.fn_register_fiado_payment_in_cash();
CREATE TRIGGER tr_sale_details_reduce BEFORE INSERT ON public.sale_details FOR EACH ROW EXECUTE FUNCTION public.fn_reduce_stock_from_sales();
CREATE TRIGGER tr_update_fiado_on_payment AFTER INSERT OR DELETE OR UPDATE ON public.debt_payments FOR EACH ROW EXECUTE FUNCTION public.update_fiado_status();
CREATE TRIGGER tr_waste_reduce AFTER INSERT ON public.waste FOR EACH ROW EXECUTE FUNCTION public.update_stock_from_waste();
CREATE TRIGGER trg_sanitize_product_codes BEFORE INSERT OR UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.fn_sanitize_product_codes();
CREATE TRIGGER trg_sync_product_name_update AFTER UPDATE OF name ON public.products FOR EACH ROW EXECUTE FUNCTION public.trg_sync_product_name();
CREATE TRIGGER trg_waste_delete AFTER DELETE ON public.waste FOR EACH ROW EXECUTE FUNCTION public.fn_restore_stock_on_waste_delete();

-- ---------------------------------------------------------------------
-- 7b. SESIONES DE USUARIO
-- ---------------------------------------------------------------------
-- Cada inicio de sesión crea un token aquí; permisos y estado se leen siempre de empleados.
CREATE TABLE public.sesiones (
  token       uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  empleado_id uuid        NOT NULL REFERENCES public.empleados(id) ON DELETE CASCADE,
  creado      timestamptz NOT NULL DEFAULT now(),
  ultimo_uso  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sesiones_empleado_id_idx ON public.sesiones (empleado_id);

-- ---------------------------------------------------------------------
-- 8. PERMISOS
-- ---------------------------------------------------------------------
-- La app se conecta con la clave publicable (rol anon). Igual que en la instalación original,
-- las tablas no tienen RLS y el rol anon puede leer y escribir en ellas.
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------
-- 9. DATOS INICIALES
-- ---------------------------------------------------------------------
-- Ficha de la empresa: el nombre, RUC, dirección, teléfono y logo se editan en Configuración.
INSERT INTO public.empresa_config (nombre_empresa) VALUES ('MI EMPRESA');

-- Usuario administrador para el primer ingreso (escribiendo solo "admin", la app completa el correo).
INSERT INTO public.empleados (nombre, email, password, rol, estado, permisos)
VALUES ('Administrador', 'admin@gestorpro.com', 'cambiar123', 'Administrador', 'ACTIVO', '{"sistema_acceso_total": true}');

COMMIT;

-- Recarga la API de Supabase para que vea las tablas nuevas de inmediato.
NOTIFY pgrst, 'reload schema';
